export const SONG_SEARCH_REQUEST = "SONG_SEARCH_REQUEST";
export const SONG_SEARCH_SUCCESS = "SONG_SEARCH_SUCCESS";
export const SONG_SEARCH_FAIL = "SONG_SEARCH_FAIL";

export const SONG_SELECT_REQUEST = "SONG_SELECT_REQUEST";
export const SONG_SELECT_SUCCESS = "SONG_SELECT_SUCCESS";
export const SONG_SELECT_FAIL = "SONG_SELECT_FAIL";

export const RECOMMENDATIONS_REQUEST = "RECOMMENDATIONS_REQUEST";
export const RECOMMENDATIONS_SUCCESS = "RECOMMENDATIONS_SUCCESS";
export const RECOMMENDATIONS_FAILURE = "RECOMMENDATIONS_FAILURE";
